<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>WeaponMastery</RootNamespace>
    <AssemblyName>WeaponMastery</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <!-- Plugin Version -->
    <Version>1.3.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AnimationSystem.Types">
      <HintPath>References\Tarkov\AnimationSystem.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>References\Tarkov\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>References\Bepinex\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>References\SPT\spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>References\Tarkov\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>References\Tarkov\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <Target Name="PackagePlugin" AfterTargets="Build" Condition="'$(SkipDeploy)' != 'true'">
    <ItemGroup>
      <OutputDLL Include="$(TargetPath)" />
    </ItemGroup>
    <!-- Creates a release zip file -->
    <RemoveDir Directories="$(ProjectDir)release" />
    <Copy SourceFiles="@(OutputDLL);" DestinationFolder="$(ProjectDir)release\WeaponMastery\BepInEx\plugins\%(RecursiveDir)" />
    <Delete Files="$(ProjectDir)release\WeaponMastery-$(Configuration)-$(Version).zip" Condition="'$(Configuration)' == 'Debug'" />
    <Delete Files="$(ProjectDir)release\WeaponMastery-$(Version).zip" Condition="'$(Configuration)' == 'Release'" />
    <ZipDirectory SourceDirectory="$(ProjectDir)release\WeaponMastery\" Condition="'$(Configuration)' == 'Debug'" DestinationFile="$(ProjectDir)release\WeaponMastery-$(Configuration)-$(Version).zip" />
    <ZipDirectory SourceDirectory="$(ProjectDir)release\WeaponMastery\" Condition="'$(Configuration)' == 'Release'" DestinationFile="$(ProjectDir)release\WeaponMastery-$(Version).zip" />
  </Target>
</Project>
